"""add class_appreciation_audio_url

Revision ID: 27fa99301663
Revises: cd80598b771f
Create Date: 2026-05-09 17:30:54.882208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fa99301663'
down_revision = 'cd80598b771f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_appreciation_audio_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('class_appreciation_audio_url')

    # ### end Alembic commands ###
