"""add fields to competences

Revision ID: 52bcd5ab7c38
Revises: f1eb3b5ed69b
Create Date: 2026-06-06 22:19:29.861665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bcd5ab7c38'
down_revision = 'f1eb3b5ed69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('domain', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('subject')
        batch_op.drop_column('domain')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
