"""add advice to question_scores

Revision ID: 663d0ed9c3c8
Revises: eeef51342834
Create Date: 2026-06-05 12:31:23.742740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663d0ed9c3c8'
down_revision = 'eeef51342834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_scores', schema=None) as batch_op:
        batch_op.drop_column('advice')

    # ### end Alembic commands ###
