"""add level to classroom

Revision ID: c904e8f3745d
Revises: ddaa27af8883
Create Date: 2026-06-07 14:51:22.096771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c904e8f3745d'
down_revision = 'ddaa27af8883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
