"""add class_appreciation to assignment

Revision ID: cd80598b771f
Revises: efd112b46c8e
Create Date: 2026-05-09 09:32:17.486415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd80598b771f'
down_revision = 'efd112b46c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_appreciation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('class_appreciation')

    # ### end Alembic commands ###
