"""add competence_id to questions

Revision ID: ddaa27af8883
Revises: 52bcd5ab7c38
Create Date: 2026-06-07 09:13:49.677585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddaa27af8883'
down_revision = '52bcd5ab7c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competence_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'competences', ['competence_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('competence_id')

    # ### end Alembic commands ###
