"""add competences table and foreign key

Revision ID: eeef51342834
Revises: ff9b7fb70bb9
Create Date: 2026-06-04 22:14:07.798702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeef51342834'
down_revision = 'ff9b7fb70bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competence_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'competences', ['competence_id'], ['id'])
        batch_op.drop_column('competence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competence', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('competence_id')

    op.drop_table('competences')
    # ### end Alembic commands ###
