"""add classroom correction qrscore accesslog

Revision ID: efd112b46c8e
Revises: 33f940da0014
Create Date: 2026-05-09 08:54:42.837286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd112b46c8e'
down_revision = '33f940da0014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('school_year', sa.String(length=9), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=16), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('structured_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrections_public_token'), ['public_token'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('competence', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correction_id', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['correction_id'], ['corrections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correction_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['correction_id'], ['corrections.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('total_points', sa.Float(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('assignments_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['id'])
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('student_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_first_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_last_name', sa.Text(), nullable=True))
        batch_op.alter_column('alias',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('students_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['id'])
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('theme_primary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('theme_secondary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('theme_bg', sa.String(length=7), nullable=True))
        batch_op.drop_constraint(batch_op.f('teachers_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_teachers_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_email'))
        batch_op.create_unique_constraint(batch_op.f('teachers_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('theme_bg')
        batch_op.drop_column('theme_secondary')
        batch_op.drop_column('theme_primary')
        batch_op.drop_column('school')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('students_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'])
        batch_op.alter_column('alias',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('encrypted_last_name')
        batch_op.drop_column('encrypted_first_name')
        batch_op.drop_column('student_number')
        batch_op.drop_column('classroom_id')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assignments_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'])
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('total_points')
        batch_op.drop_column('date')
        batch_op.drop_column('description')
        batch_op.drop_column('classroom_id')

    op.drop_table('question_scores')
    op.drop_table('access_logs')
    op.drop_table('questions')
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrections_public_token'))

    op.drop_table('corrections')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
