"""add read_at to correction

Revision ID: ff9b7fb70bb9
Revises: bd02e6e7ae8b
Create Date: 2026-05-30 23:15:34.067379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9b7fb70bb9'
down_revision = 'bd02e6e7ae8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
